config/routes.rb
Vokabeln::Application.routes.draw do
  root :to => "users#index"
  
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions
  resources :users
  
  get '/search' => "vocables#search", :as => 'search'
  
  # Workaround for bug below (see http://stackoverflow.com/questions/3937823/weird-routing-error-in-rails-3-0)
  match '/users/:user_id/lessons/:lesson_id/vocables/:id/check(.:format)', :to => "vocables#check", :as => :check_user_lesson_vocable
  
  resources :users do
    resources :lessons do
      member do
        get 'test'
      end
      
      resources :vocables do
        member do
          get 'ask'
          # Doesn't work! Rails bug!
          #post 'check'
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lessons, :dependent => :destroy
  
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:index, :show, :new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @new_lesson ||= current_user.lessons.new if logged_in?
    
    respond_to do |format|
      format.js { render 'show.html', :layout => 'insert_content' }
      format.html
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/index.html.erb
<p>
<% unless logged_in? -%>
  <%= link_to "Login", login_path %>
  <%= link_to "Signup", signup_path %>
<% else -%>
  <%= link_to "Logout", logout_path %>
<% end -%>
</p>

<ul>
  <% for user in @users -%>
    <li><%= link_to user.username, user %></li>
  <% end -%>
</ul>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/users/show.html.erb
<% title @user.username %>

<% content_for :header_right, render('vocables/search_form') %>

<% if @user.lessons.empty? %>
  <% if @user == current_user -%>
    <p>Oh, you don't have any lessons yet! Create one:</p>
  <% else -%>
    <p>This user hasn't created any lessons yet.</p>
  <% end -%>
<% end %>
<ul id="lessons">
  <% for lesson in @user.lessons -%>
    <li class="lesson"><%= link_to lesson.name, user_lesson_path(lesson.user, lesson) %></li>
  <% end %>
  <% if @user == current_user -%>
    <li class="lesson"><%= render "lessons/form" %></li>
  <% end -%>
</ul>