config/routes.rb
Vokabeln::Application.routes.draw do
  root :to => "users#index"
  
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions
  resources :users
  
  get '/search' => "vocables#search", :as => 'search'
  
  # Workaround for bug below (see http://stackoverflow.com/questions/3937823/weird-routing-error-in-rails-3-0)
  match '/users/:user_id/lessons/:lesson_id/vocables/:id/check(.:format)', :to => "vocables#check", :as => :check_user_lesson_vocable
  
  resources :users do
    resources :lessons do
      member do
        get 'test'
      end
      
      resources :vocables do
        member do
          get 'ask'
          # Doesn't work! Rails bug!
          #post 'check'
        end
      end
    end
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :user
  has_many :vocables, :dependent => :destroy
  
  validates :name, :presence => true
  
  def saved_vocables
    vocables.reject do |vocable|
      vocable.new_record?
    end
  end
  
  def random_vocable
    # TODO: Make this more efficient (maybe with sql offset?)
    vocables[rand(vocables.size)]
  end
end

app/controllers/lessons_controller.rb
# coding: utf-8

class LessonsController < ApplicationController
  before_filter :login_required, :except => [:show]
  before_filter :is_owner, :except => [:show, :create]
  
  def show
    @lesson = Lesson.find(params[:id])
    @new_vocable ||= @lesson.vocables.build
  end
  
  def create
    @new_lesson = current_user.lessons.create(params[:lesson])
    if @new_lesson.save
      redirect_to user_lesson_path(current_user, @new_lesson)
    else
      index
      render :index
    end
  end
  
  def destroy
    lesson = Lesson.find(params[:id])
    if lesson.destroy
      redirect_to(lesson.user, :flash => { :notice => "Lesson “#{lesson.name}” was deleted." })
    else
      redirect_to user_lesson_path(lesson.user, lesson), :flash => { :error => "Lesson could not be deleted." }
    end
  end
  
  def test
    lesson = Lesson.find(params[:id])
    redirect_to ask_user_lesson_vocable_path(lesson.user, lesson, lesson.random_vocable)
  end

  private

  def is_owner
    unless Lesson.find(params[:id]).user == current_user
      redirect_to :back
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_for [@new_lesson.user, @new_lesson] do |f| %>
  <div>
    <%= f.error_messages my_error_opts %>
  </div>
  <div>
    <%= f.label :name, :class => :hidden %>
    <%= f.text_field :name, { :placeholder => "Name", :required => true } %>
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/show.html.erb
<% title @lesson.name -%>

<% content_for :header do -%>
  <h1><%= raw breadcrumb([@lesson.user.username, user_path(@lesson.user)], @lesson.name) %></h1>
<% end -%>

<% content_for :header_right do -%>
  <%= link_to "Test yourself", test_user_lesson_path(@lesson.user, @lesson), :class => 'button' if @lesson.user == current_user %>
<% end -%>

<%= render :partial => 'vocables/table', :locals => { :vocables => @lesson.saved_vocables } %>

<%= render 'vocables/form' if @lesson.user == current_user %>

<div class="actions">
  <%= link_to 'Delete lesson', user_lesson_path(@lesson), :confirm => "This lesson and all it's vocables will be deleted. Are you sure?", :method => :delete, :class => 'delete-button' if @lesson.user == current_user %>
</div>