config/routes.rb
Vokabeln::Application.routes.draw do
  root :to => "users#index"
  
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions
  resources :users
  
  get '/search' => "vocables#search", :as => 'search'
  
  # Workaround for bug below (see http://stackoverflow.com/questions/3937823/weird-routing-error-in-rails-3-0)
  match '/users/:user_id/lessons/:lesson_id/vocables/:id/check(.:format)', :to => "vocables#check", :as => :check_user_lesson_vocable
  
  resources :users do
    resources :lessons do
      member do
        get 'test'
      end
      
      resources :vocables do
        member do
          get 'ask'
          # Doesn't work! Rails bug!
          #post 'check'
        end
      end
    end
  end
end

app/models/vocable.rb
class Vocable < ActiveRecord::Base
  belongs_to :lesson
  has_many :attempts
  
  validates_presence_of :foreign, :translation
  
  def check_foreign guess
    create_attempt(foreign == guess)
  end
  
  def self.search query
    query = "%#{query}%"
    find :all, :conditions => ['`foreign` LIKE ? OR `translation` LIKE ?', query, query]
  end
  
  private
  
  def create_attempt success
    attempts.create :success => success
    success
  end
end

app/controllers/vocables_controller.rb
class VocablesController < ApplicationController
  before_filter :is_owner, :except => [:create, :search]
  
  def create
    redirect_to :back unless User.find(params[:user_id]) == current_user
    
    @lesson = Lesson.find(params[:lesson_id])
    @new_vocable = @lesson.vocables.create(params[:vocable])
    
    respond_to do |format|
      if @new_vocable.save
        # format.json { render :json => @new_vocable }
        format.js
        format.html { redirect_to @lesson }
      else
        # format.json { render :json => @new_vocable.errors }
        format.js
        format.html do
          render 'lessons/show'
        end
      end
    end
  end
  
  def destroy
    @vocable = Vocable.find(params[:id])
    @vocable.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to vocable.lesson }
    end
  end
  
  def ask
    @vocable = Vocable.find(params[:id])
  end
  
  def check
    vocable = Vocable.find(params[:id])
    success = vocable.check_foreign(params[:vocable][:foreign])
    if success
      flash[:success] = ["Fine", "Well done"].sample
    else
      flash[:error] = "Nope, the expression is #{vocable.foreign}"
    end
    redirect_to ask_user_lesson_vocable_path(vocable.lesson.user, vocable.lesson, vocable.lesson.random_vocable)
  end
  
  def search
    query = params[:q]
    unless query.empty?
      @vocables = Vocable.search(query)
      
      respond_to do |format|
        format.js { render 'search.html', :layout => 'insert_content' }
        format.html
      end
    else
      redirect_to root_path
    end
  end

  private

  def is_owner
    unless Vocable.find(params[:id]).lesson.user == current_user
      redirect_to :back
    end
  end
end

app/helpers/vocables_helper.rb
module VocablesHelper
end

app/views/vocables/_form.html.erb
<% form_for [@new_vocable.lesson.user, @new_vocable.lesson, @new_vocable], :remote => true do |f| %>
  <%= f.error_messages my_error_opts %>
  <%= f.label :foreign, :class => :hidden %>
  <%= f.text_field :foreign, { :placeholder => "Word", :autofocus => true, :required => true } %>
  <%= f.label :translation, :class => :hidden %>
  <%= f.text_field :translation, { :placeholder => "Translation", :required => true } %>
  <%= f.submit %>
<% end %>

app/views/vocables/_search_form.html.erb
<%= form_tag search_path, :remote => true, :method => :get do %>
  <%= text_field_tag :q, "", :placeholder => "Search", :autofocus => true, :id => 'search-field' %>
  <%= submit_tag "Start", :name => nil, :class => 'hidden' %>
<% end -%>

app/views/vocables/_table.html.erb
<table class="vocables" id="vocables">
  <colgroup>
    <col width="35%" />
    <col width="35%" />
    <col width="10%" />
    <col width="20%" />
  </colgroup>
  <thead>
    <tr>
      <th>Foreign word</th>
      <th>Translation</th>
      <th><span class="hidden">Delete</span></th>
      <th><span class="hidden">Success</span></th>
    </tr>
  </thead>
  <tbody>
    <tr id="no-vocables-notice" class="<%= "totally-hidden" unless vocables.empty? %>">
      <td colspan="3">No vocables yet. Use the form below to add some.</td>
    </tr>
    <%= render :partial => 'vocables/table_row', :collection => vocables, :as => :vocable %>
  </tbody>
</table>

app/views/vocables/_table_row.html.erb
<tr class="vocable" id="vocable_<%= vocable.id %>">
  <td><%= vocable.foreign %></td>
  <td><%= vocable.translation %></td>
  <td><%= link_to 'Delete', user_lesson_vocable_path(vocable.lesson.user, vocable.lesson, vocable), :method => :delete, :class => 'delete-link', :remote => true if vocable.lesson.user == current_user %></td>
  <td>
    <ol class="attempts">
      <% for attempt in vocable.attempts -%>
        <li class="attempt <%= attempt.success? ? "successful" : "unsuccessful" %>">
          <span class="hidden"><%= attempt.success? ? "Successful" : "Unsuccessful" %></span>
        </li>
      <% end -%>
    </ol>
  </td>
</tr>

app/views/vocables/ask.html.erb
<% lesson = @vocable.lesson -%>

<% content_for :header do -%>
  <h1><%= raw breadcrumb([lesson.user.username, lesson.user], [lesson.name, user_lesson_path(lesson.user, lesson)], "Test") %></h1>
<% end -%>

<%= form_for [lesson.user, lesson, @vocable], :url => check_user_lesson_vocable_path(lesson, @vocable), :html => { :class => 'ask_vocable' } do |f| -%>
  <%= f.label :foreign, raw("Translate <b>“#{@vocable.translation}”</b>") %>
  <%= f.text_field :foreign, :placeholder => 'Translation', :value => '', :autofocus => true %>
<% end -%>

app/views/vocables/create.js.erb
(function() {
  $('#new_vocable .errorExplanation').remove();
  <% if @new_vocable.errors.empty? -%>
    $('#vocables tbody').append("<%= escape_javascript(render :partial => 'table_row', :object => @new_vocable, :as => :vocable) %>");
    $('#no-vocables-notice').addClass('totally-hidden');
    $('#new_vocable').get(0).reset();
    $('#vocable_foreign').focus();
  <% else -%>
    $('#new_vocable').prepend("<%= escape_javascript(error_messages_for @new_vocable, my_error_opts) %>");
  <% end -%>
})();

app/views/vocables/destroy.js.erb
$('#vocable_<%= @vocable.id %>').fadeOut(400, function() {
  $(this).remove();
  if ($('.vocable').length == 0) {
    $('#no-vocables-notice').removeClass('totally-hidden');
  }
});

app/views/vocables/search.html.erb
<% content_for :header_right, render('vocables/search_form') %>

<% if @vocables.empty? -%>
  <p>Nothing found :-(</p>
<% else -%>
  <%= render :partial => 'table', :locals => { :vocables => @vocables } %>
<% end -%>